name: samuel_s_application4
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=3.4.4 <4.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  flutter_riverpod: ^2.5.1
  equatable: ^2.0.5
  shared_preferences: ^2.3.0
  connectivity_plus: ^6.0.4
  country_pickers: ^3.0.1
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
        - asset: assets/fonts/InterSemiBold.ttf
          weight: 600
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
        - asset: assets/fonts/InterBold.ttf
          weight: 700
